travis:
  secure:
    BINSTAR_TOKEN: Z8YLOlsN4SFijtI4MMyMlRiNcJabhsnVjC1TNJAq5CzM5jyC8rb8KYJ6RpjnLfJLT1TmObHlYttkJ8pdWIpYqhzHGDkY+efQVS/7s0RpWDmAAl0aqFGIK+eH0q1zhPcgAqAV9RFd5KuucgV4vRPa1FTdDKpXbB1y+L/AA3pK4GQCBE0nVf3FUoKDz4k4uHdeRzE8sULC72DdiwuxfUTyToabdjn9ieaR79R8O3ZYSwrhqSMozj72uWnJX9JF1wzLqb//x+C9Q1p0O8DNq/4LqfUZy9dBHjglpXPqkoCFevj7dQsbiO1ALJNq2YWh8YNtnAhgYDTI5Vn7hEtEzgTEB4OJ1trY95huOFiUYaZFzZUHuF+Tks7yeQs1UOhJDUhjVDwLWNx6xtu6F4XhOzQH6wg3fiJg2FosqxWzpCngiee1DGf5+bWCpHOu+EC+oya+0v5ZRjs2y2MVctFb54JXDwzncuje59c8PPY30HT00gzZuI7I/AE1zxno3/R+FLlQuFCZNFpBa26IjQtMyzVoB6GuI1z1RAY0dygnGi5NIHekhJTSDY53h9fSB46C6lR/aGW2uSB9HWwRfAc6+wTLZFuYx3Q3Lq18HWBfav9P2hWDoHjNmlm8mP4ga/dHDf9NYMcQQEqcLlrf9WJr5EX/v9Q10kB1lZfXjxrWmE/DrS0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
